### PR TITLE
Fixing bugs in time-varying R + other fixes

### PR DESCRIPTION
**Pull request by thibautjombart**
This follows PR https://github.com/reconhub/projections/pull/30 by @stephaneghozzi

Will be easier to add commits to this one without having to PR against your branch ;)

### CODE REVIEW

**Comment by thibautjombart** [comment]
I think this is ready for review @stephaneghozzi (but cannot tag you until you accepted the write access to the repo, I think). In a nutshell: 

* **scaling the serial interval**: former code was implicitly assuming `si(0) = 0` but was never actually testing it; I think this ended up ignoring si(0) in the calculations, but the pmf was not rescaled to account for it; it resulted that the forces of infection were generally lower than they should, which I think explains why all new references were slightly higher in numbers than previous objects; now, we ask the user to specify that SI from delay = 1 (not 0); if specified as a `distcrete`, we ignore `si$d(0)` and rescale the rest so the PMF sums to 1

* **differences in plots**: 
    + all plots have been updated
    + after fixing the above, some plots for the Ebola simulations were grossly over-shooting; this is because the SI was grossly wrong, and was exponential with a mass ~ 0.25 for si(0); so fixing the rescaling led to over-shooting, which I have now fixed using a more realistic SI as well as R

* **tests against references**: 
    + generally speaking, these are to be avoided as a bit lazy and prone to errors (one really needs to check the reference, a lot)
    + where relevant, I have replaced these tests by more meaningful tests
    + I have removed redundant objects accordingly
    + for tests still using references, I have updated these and checked that the outputs made sense

* **other stuff**:
    + I have updated the doc where needed
    + I have fixed a bug in `as.data.frame` when using `long = TRUE`, where `sim` was wrong
    + I have added a test against this bug

* **current status**: the package passes the check on:
```r
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock        
```

**Comment by stephaneghozzi** [comment]
I reread the code and redid some plots. It all looks good up to one test that fails: [test-subset.R](https://github.com/reconhub/projections/blob/bugfix-project-R_t/tests/testthat/test-subset.R) 😅

To be precise it failed on R 4.0.1 on macOS and Windows, but passed on R 3.6.3 on Windows...!

The reason is the removal of one attribute for the variable `subset_*` but not `ref_*`, with the pair supposed to be identical. The first example in the test:
```r
    dat <- c(0, 2, 2, 3, 3, 5, 5, 5, 6, 6, 6, 6)
    i <- incidence::incidence(dat)


    ## example with a function for SI
    si <- distcrete::distcrete("gamma", interval = 1L,
                               shape = 1.5,
                               scale = 2, w = 0)
    
    x <- project(i, runif(100, 0.8, 1.9), si, n_days = 30)

    subset_1 <- subset(x, from = 15, to = 20, sim = 1:10)
    attributes(subset_1)$class <- attributes(subset_1)$class[(1:2)]
    ref_1 <- x[get_dates(x) %in% 15:20, 1:10]
    expect_identical(ref_1, subset_1)
```

I'd suggest just removing the six lines with `attributes(subset_*)$class <- attributes(subset_*)$class[(1:2)]` (or alternatively adding similar lines for  `ref_*`). When I do that, check() is happy with all 3 combinations of R versions and OS tested (no error, warning or note). Let me know if you'd like more precise specifications.

However since I'm not sure why one attribute is removed, I didn't commit any change and will let you decide...

Otherwise, I think it's all good and ready to be merged. 👌👍🙂

**Comment by thibautjombart** [comment]
Not quite sure why this was there. Many thanks for flagging the issue. Running checks and wil push changes right after.

**Comment by thibautjombart** [comment]
Got approval from @stephaneghozzi on a different forum. Failures on CI seem to come from a different version of `vdiffr` used.

**Pull request merged**
